require('./bower_components/angular/angular.js')
require('./bower_components/angular-route/angular-route.js')
require('./bower_components/angular-resource/angular-resource.js')
require('./bower_components/angular-animate/angular-animate.js')
require('./bower_components/angular-sanitize/angular-sanitize.js')
require('./bower_components/angular-aria/angular-aria.js')
require('./bower_components/angular-messages/angular-messages.js')